apiVersion: secret.jenkins-x.io/v1alpha1
kind: Schema
spec:
  objects:
  - name: jenkins-x-chartmuseum
    properties:
    - name: username
      question: chartmuseum repository user name
      help: The username used to authenticate with chartmuseum (the helm repository)
      defaultValue: admin
    - name: password
      question: chartmuseum repository password
      help: The password to authenticate with the chartmuseum (the helm repository)
      minLength: 5
      maxLength: 41
      generator: password

