# Source: jxboot-helmfile-resources/templates/environments.yaml
apiVersion: jenkins.io/v1
kind: Environment
metadata:
  labels:
    env: "production"
    team: jx
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: "production"
  namespace: jx
spec:
  kind: Permanent
  label: Production
  promotionStrategy: "Manual"
  namespace: "jx-production"
